### ISSUE TITLE
Querying reward info returns 0

### ISSUE THREAD

**Issue by andreivirtosu** [Mirror-Protocol/mirror.js#6] opened 2021-02-26 11:18 UTC
Tried a simple query to get the pending rewards, and getting the pending_reward result set to zero.
```
let token = 'terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2';
const result = await mirror.staking.getRewardInfo(account, token);
```

Result:
```
{
  staker: 'xxx',
  reward_infos: [
    {
      asset_token: 'terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2',
      index: '44.62516407102563644',
      bond_amount: 'xxx',
      pending_reward: '0'
    }
  ]
}

**Comment by serwer20** [comment] 2021-04-03 15:07
same issue here

**Comment by RylandCapital** [comment] 2021-04-30 10:38
I get the exact same thing, I get the correct everything, bond amount etc. pending rewards always 0.

**Comment by nono2357** [comment] 2021-05-08 18:03
I have the same issue too.

**Comment by sjoerdmaessen** [comment] 2021-05-14 14:22
As it turns out you need to have a certain level of unclaimed rewards before its returned in the response. 

For example:
```
{
  staker: 'xxx',
  reward_infos: [
    {
      asset_token: 'terra1m6j6j9gw728n82k78s0j9kq8l5p6ne0xcc820p',
      index: '2.164914379838601868',
      bond_amount: '936563',
      pending_reward: '0'
    }
  ]
}
{
  staker: 'terra1y4qgp922m5xtr0k334yeeekp65zxmy4ry9fyvg',
  reward_infos: [
    {
      asset_token: 'terra1qelfthdanju7wavc5tq0k5r0rhsyzyyrsn09qy',
      index: '0.553685413820174148',
      bond_amount: '1000000',
      pending_reward: '333517'
    }
  ]
}
```

Although on https://terra.mirror.finance/my the following rewards are visible:
mAMC: 333636
mGME: 0.001703

Seems like that 0.001703 is simply to small resulting in a pending_reward value of '0' in the response. I haven't examined where the cutoff is.

In other words, for development, for now, use bigger accounts or wait longer. Hope this helps for others facing this issue.

**Comment by RylandCapital** [comment] 2021-05-14 14:42
Its not because the rewards are to small. if you unpool your asset the reward becomes pending. all your pending rewards will show no matter how small (up to 6 demicals) if you atleast have some of that asset unpooled in your holding tab. The issue is how they define "pending". in order to get your unclaimed rewards you have to use the reward_info terra call to get your index and do some math with the pools reward index. someone posted it in telegram, looking for it now for you guys.

**Comment by 0xslipk** [comment] 2021-06-04 14:03
@yandreiy @RylandCapital @nono2357 @sjoerdmaessen hey guys, the problem is not related to `pending_reward === 0`. The `pending_reward` don't mean that you have something unclaimed in your stake pools. The pending rewards in the pool are rewards waiting to ve distributed for the [MirrorContractFactory](https://github.com/Mirror-Protocol/mirror-contracts/blob/ea365522d29132d620f83fc476067179eceb8422/contracts/mirror_factory/src/contract.rs#L462-L547).

You can also see and example of this [here](https://github.com/Mirror-Protocol/mirror.js/blob/main/integration-test/index.ts#L275-L282).

If you want to calculate the current rewards that you have ready for claim. The way to do it is like this:
```js
import { LCDClient, Dec } from '@terra-money/terra.js';
import { Mirror } from '@mirror-protocol/mirror.js';

// default -- uses Columbus-4 core contract addresses
const mirror = new Mirror();

// Get all reward_infos in the pool
const rewards = await mirror.staking.getRewardInfo("<staker_address>");
// Get the staking pool info for a mAsset
const poolInfo = await mirror.staking.getPoolInfo("<mAsset_contract_address>");
// Find the reward info for a mAsset
const mAssetRewardInfo = rewards.reward_infos.find((rewardInfo) =>
  rewardInfo.asset_token === poolInfo.asset_token,
);
// Get the same value as  https://terra.mirror.finance
const rewardAmount = new Dec(poolInfo.reward_index)
  .sub(mAssetRewardInfo.index)
  .mul(mAssetRewardInfo.bond_amount)
  .add(mAssetRewardInfo.pending_reward);
```

**Comment by pmioduszewski** [comment] 2021-06-25 11:00
> @yandreiy @RylandCapital @nono2357 @sjoerdmaessen hey guys, the problem is not related to `pending_reward === 0`. The `pending_reward` don't mean that you have something unclaimed in your stake pools. The pending rewards in the pool are rewards waiting to ve distributed for the [MirrorContractFactory](https://github.com/Mirror-Protocol/mirror-contracts/blob/ea365522d29132d620f83fc476067179eceb8422/contracts/mirror_factory/src/contract.rs#L462-L547).
> 
> You can also see and example of this [here](https://github.com/Mirror-Protocol/mirror.js/blob/main/integration-test/index.ts#L275-L282).
> 
> If you want to calculate the current rewards that you have ready for claim. The way to do it is like this:
> 
> ```js
> import { LCDClient, Dec } from '@terra-money/terra.js';
> import { Mirror } from '@mirror-protocol/mirror.js';
> 
> // default -- uses Columbus-4 core contract addresses
> const mirror = new Mirror();
> 
> // Get all reward_infos in the pool
> const rewards = await mirror.staking.getRewardInfo("<staker_address>");
> // Get the staking pool info for a mAsset
> const poolInfo = await mirror.staking.getPoolInfo("<mAsset_contract_address>");
> // Find the reward info for a mAsset
> const mAssetRewardInfo = rewards.reward_infos.find((rewardInfo) =>
>   rewardInfo.asset_token === poolInfo.asset_token,
> );
> // Get the same value as  https://terra.mirror.finance
> const rewardAmount = new Dec(poolInfo.reward_index)
>   .sub(mAssetRewardInfo.index)
>   .mul(mAssetRewardInfo.bond_amount)
>   .add(mAssetRewardInfo.pending_reward);
> ```

What's the recipe now sir? 🙃 (v2)
```js
const rewardAmount = new Dec(poolInfo.reward_index)
   .sub(mAssetRewardInfo.index) // <------ THIS KEY MISSING AFTER V2 UPDATE
   .mul(mAssetRewardInfo.bond_amount)
   .add(mAssetRewardInfo.pending_reward);
```

**Comment by 0xslipk** [comment] 2021-06-25 12:07
> > @yandreiy @RylandCapital @nono2357 @sjoerdmaessen hey guys, the problem is not related to `pending_reward === 0`. The `pending_reward` don't mean that you have something unclaimed in your stake pools. The pending rewards in the pool are rewards waiting to ve distributed for the [MirrorContractFactory](https://github.com/Mirror-Protocol/mirror-contracts/blob/ea365522d29132d620f83fc476067179eceb8422/contracts/mirror_factory/src/contract.rs#L462-L547).
> > You can also see and example of this [here](https://github.com/Mirror-Protocol/mirror.js/blob/main/integration-test/index.ts#L275-L282).
> > If you want to calculate the current rewards that you have ready for claim. The way to do it is like this:
> > ```js
> > import { LCDClient, Dec } from '@terra-money/terra.js';
> > import { Mirror } from '@mirror-protocol/mirror.js';
> > 
> > // default -- uses Columbus-4 core contract addresses
> > const mirror = new Mirror();
> > 
> > // Get all reward_infos in the pool
> > const rewards = await mirror.staking.getRewardInfo("<staker_address>");
> > // Get the staking pool info for a mAsset
> > const poolInfo = await mirror.staking.getPoolInfo("<mAsset_contract_address>");
> > // Find the reward info for a mAsset
> > const mAssetRewardInfo = rewards.reward_infos.find((rewardInfo) =>
> >   rewardInfo.asset_token === poolInfo.asset_token,
> > );
> > // Get the same value as  https://terra.mirror.finance
> > const rewardAmount = new Dec(poolInfo.reward_index)
> >   .sub(mAssetRewardInfo.index)
> >   .mul(mAssetRewardInfo.bond_amount)
> >   .add(mAssetRewardInfo.pending_reward);
> > ```
> 
> What's the recipe now sir? 🙃 (v2)
> 
> ```js
> const rewardAmount = new Dec(poolInfo.reward_index)
>    .sub(mAssetRewardInfo.index) // <------ THIS KEY MISSING AFTER V2 UPDATE
>    .mul(mAssetRewardInfo.bond_amount)
>    .add(mAssetRewardInfo.pending_reward);
> ```

On Mirror v2 is very simple:

```js
const rewardAmount = mAssetRewardInfo.pending_reward;
```

The Mirror v2 don't have the index, because the Mirror Staking contract calculate the `pending_reward` when you execute the query. Internally the contract uses the index and return a clean value.

You can see more about this [here](https://github.com/Mirror-Protocol/mirror-contracts/blob/master/contracts/mirror_staking/src/rewards.rs#L194-L211).

**Comment by yun-yeo** [comment] 2021-07-13 00:58
@jarcodallo Thanks for your reply :) 

If no further issue here, I will close the issue.

**Closed as completed by yun-yeo** 2021-07-13 00:58 UTC
